"""Generate paper/numbers.tex (LaTeX macros) and paper tables from results/tables,
copy figures, and compile paper/main.tex with tectonic."""
from __future__ import annotations

import json
import shutil
import subprocess

import pandas as pd

from nifty_mtl.config import FIGURES, RESULTS, ROOT, TABLES

PAPER = ROOT / "paper"
(PAPER / "figures").mkdir(exist_ok=True)


def macro(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def fmt(x, nd=2, pct=False, sign=False):
    if pd.isna(x):
        return "--"
    if pct:
        s = f"{x*100:{'+' if sign else ''}.{nd}f}\\%"
    else:
        s = f"{x:{'+' if sign else ''}.{nd}f}"
    return s


def main():
    main_tbl = pd.read_csv(TABLES / "main_results.csv", index_col=[0, 1])
    sens = pd.read_csv(TABLES / "sensitivity.csv", index_col=0)
    yearly = pd.read_csv(TABLES / "yearly.csv", index_col=0)
    static_ic = pd.read_csv(TABLES / "static_model_ic.csv", index_col=0)
    kpis = json.loads((TABLES / "shap_kpis.json").read_text())
    att = json.loads((TABLES / "attention_concentration.json").read_text())
    best = json.loads((RESULTS / "best_params.json").read_text())
    gi = pd.read_csv(TABLES / "shap_group_importance.csv", index_col=0).iloc[:, 0]
    fi = pd.read_csv(TABLES / "shap_feature_importance.csv", index_col=0).iloc[:, 0]
    reg = pd.read_csv(TABLES / "failure_regimes.csv", index_col=[0, 1])

    lines = ["% auto-generated by scripts/make_paper.py -- do not edit"]
    key = {"MTL (ours)": "Mtl", "MTL no-graph": "NoGraph", "MTL return-only": "RetOnly", "MTL no-cost": "NoCost",
           "Momentum": "Mom", "Inverse-vol": "InvVol", "Logistic": "Logit", "Random": "Rand", "Nifty 50": "Nifty"}
    for period, pk in [("all_oos", "All"), ("test", "Test"), ("holdout", "Hold")]:
        if period not in main_tbl.index.get_level_values(0):
            continue
        sub = main_tbl.loc[period]
        for strat, sk in key.items():
            if strat not in sub.index:
                continue
            r = sub.loc[strat]
            lines += [macro(f"{sk}{pk}Sharpe", fmt(r.sharpe)), macro(f"{sk}{pk}Cagr", fmt(r.cagr, 1, pct=True)),
                      macro(f"{sk}{pk}Mdd", fmt(r.max_drawdown, 1, pct=True)), macro(f"{sk}{pk}Win", fmt(r.win_rate, 1, pct=True)),
                      macro(f"{sk}{pk}Pf", fmt(r.profit_factor)), macro(f"{sk}{pk}Ic", fmt(r.get("mean_ic", float("nan")), 3)),
                      macro(f"{sk}{pk}Ir", fmt(r.get("information_ratio", float("nan")))),
                      macro(f"{sk}{pk}Sortino", fmt(r.sortino)), macro(f"{sk}{pk}Calmar", fmt(r.calmar)),
                      macro(f"{sk}{pk}Weeks", int(r.n_weeks))]
            if "sharpe_ci_lo" in r and not pd.isna(r.sharpe_ci_lo):
                lines.append(macro(f"{sk}{pk}SharpeCi", f"[{fmt(r.sharpe_ci_lo)}, {fmt(r.sharpe_ci_hi)}]"))
    for k, v in best["params"].items():
        lines.append(macro("best" + k.replace("_", ""), f"{v:.2g}" if isinstance(v, float) else str(v).replace("_", "\\_")))
    lines += [macro("shapTopFive", fmt(kpis["top5_share_of_mean_abs_shap"], 0, pct=True)),
              macro("shapTopTen", fmt(kpis["top10_share"], 0, pct=True)),
              macro("shapGraphShare", fmt(kpis["graph_share"], 0, pct=True)),
              macro("attLastFour", fmt(att["share_last_4w"], 0, pct=True)),
              macro("attLastTwelve", fmt(att["share_last_12w"], 0, pct=True)),
              macro("attFirstTwelve", fmt(att["share_first_12w"], 0, pct=True)),
              macro("topFeatureOne", fi.index[0].replace("_", "\\_")), macro("topFeatureTwo", fi.index[1].replace("_", "\\_")),
              macro("topFeatureThree", fi.index[2].replace("_", "\\_")),
              macro("topGroup", gi.index[0].replace("_", "\\_"))]
    for split in ["val", "test", "holdout"]:
        for v in static_ic.index:
            lines.append(macro(f"staticIc{v.replace('_', '').title()}{split.title()}", fmt(static_ic.loc[v, split], 3)))
    for s in sens.index:
        k = "sens" + "".join(ch for ch in s.title() if ch.isalnum())
        lines.append(macro(k, fmt(sens.loc[s, "sharpe"])))
    for (rg, bk), r in reg.iterrows():
        k = "reg" + "".join(ch for ch in (rg + bk).title() if ch.isalnum()).replace("<", "Lt").replace(">", "Ge")
        lines.append(macro(k + "Ic", fmt(r.mean_ic, 3))); lines.append(macro(k + "Sharpe", fmt(r.port_sharpe)))
    (PAPER / "numbers.tex").write_text("\n".join(lines) + "\n")

    # ---- LaTeX tables
    sub = main_tbl.loc["all_oos"].reindex(list(key)).dropna(how="all")
    cols = [("sharpe", "Sharpe", 2), ("cagr", "CAGR", None), ("max_drawdown", "MDD", None), ("win_rate", "Win", None),
            ("profit_factor", "PF", 2), ("information_ratio", "IR", 2), ("mean_ic", "IC", 3), ("avg_weekly_turnover", "Turn.", 2)]
    rows = []
    for strat, r in sub.iterrows():
        cells = []
        for c, _, nd in cols:
            v = r.get(c, float("nan"))
            cells.append(fmt(v, 1, pct=True) if nd is None else fmt(v, nd))
        ci = f" {{\\scriptsize[{fmt(r.sharpe_ci_lo)}, {fmt(r.sharpe_ci_hi)}]}}" if not pd.isna(r.get("sharpe_ci_lo", float("nan"))) else ""
        cells[0] += ci
        name = f"\\textbf{{{strat}}}" if strat == "MTL (ours)" else strat
        rows.append(name + " & " + " & ".join(cells) + " \\\\")
    tbl = ["\\begin{tabular}{l" + "r" * len(cols) + "}", "\\toprule",
           "Strategy & " + " & ".join(h for _, h, _ in cols) + " \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]
    (PAPER / "tab_main.tex").write_text("\n".join(tbl) + "\n")

    rows = []
    for period, pk in [("test", "Test 2023-H2--2024"), ("holdout", "Holdout 2025--2026")]:
        if period not in main_tbl.index.get_level_values(0):
            continue
        s2 = main_tbl.loc[period]
        for strat in ["MTL (ours)", "Momentum", "Logistic", "Nifty 50"]:
            if strat in s2.index:
                r = s2.loc[strat]
                rows.append(f"{pk} & {strat} & {fmt(r.sharpe)} & {fmt(r.cagr,1,pct=True)} & {fmt(r.max_drawdown,1,pct=True)} & {fmt(r.win_rate,1,pct=True)} & {fmt(r.get('mean_ic', float('nan')),3)} \\\\")
    tbl = ["\\begin{tabular}{llrrrrr}", "\\toprule", "Period & Strategy & Sharpe & CAGR & MDD & Win & IC \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]
    (PAPER / "tab_periods.tex").write_text("\n".join(tbl) + "\n")

    rows = [f"{s.replace('%', '\\%')} & {fmt(r.sharpe)} & {fmt(r.cagr,1,pct=True)} \\\\" for s, r in sens.iterrows()]
    tbl = ["\\begin{tabular}{lrr}", "\\toprule", "Setting & Sharpe & CAGR \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]
    (PAPER / "tab_sens.tex").write_text("\n".join(tbl) + "\n")

    rows = [f"{str(y)} & {fmt(r.mtl_return,1,pct=True)} & {fmt(r.nifty_return,1,pct=True)} & {fmt(r.mtl_sharpe)} & {fmt(r.nifty_sharpe)} & {int(r.weeks)} \\\\" for y, r in yearly.iterrows()]
    tbl = ["\\begin{tabular}{lrrrrr}", "\\toprule", "Year & MTL return & Nifty return & MTL Sharpe & Nifty Sharpe & Weeks \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]
    (PAPER / "tab_yearly.tex").write_text("\n".join(tbl) + "\n")

    rows = []
    for (rg, bk), r in reg.iterrows():
        rows.append(f"{rg} & {bk.replace('%', '\\%').replace('<', '$<$').replace('>=', '$\\geq$')} & {int(r.weeks)} & {fmt(r.mean_ic,3)} & {fmt(r.ic_t_stat,1)} & {fmt(r.port_sharpe)} \\\\")
    tbl = ["\\begin{tabular}{llrrrr}", "\\toprule", "Regime & Bucket & Weeks & IC & $t$ & Sharpe \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]
    (PAPER / "tab_regimes.tex").write_text("\n".join(tbl) + "\n")

    for f in FIGURES.glob("*.pdf"):
        shutil.copy(f, PAPER / "figures" / f.name)
    r = subprocess.run(["tectonic", "main.tex"], cwd=PAPER, capture_output=True, text=True)
    print(r.stdout[-800:], r.stderr[-1500:])
    print("paper ->", PAPER / "main.pdf", (PAPER / "main.pdf").exists())


if __name__ == "__main__":
    main()
